--CREATE TABLE USUARIO(ID INTEGER PRIMARY KEY NOT NULL, NOME VARCHAR(200), EMAIL VARCHAR(255), SENHA VARCHAR(100), TIPO_USUARIO VARCHAR(100), ATIVO BOOLEAN DEFAULT TRUE);

--CREATE SEQUENCE SEQ_USUARIO START WITH 1;